apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-presentation
  namespace: presentation
  labels:
    app: api-presentation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-presentation
  template:
    metadata:
      labels:
        app: api-presentation
    spec:
      containers:
        - name: api-presentation
          image: oxerael/so-apresentacao:0.0.5
          resources:
            requests:
              memory: 70Mi
              cpu: 500m
            limits:
              memory: 80Mi
              cpu: 500m
          ports:
            - containerPort: 3000
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
